id: P6860A4A4
initial_creation_type: input
source_metadata:
  title: Hagiography of sPyan snga Glang ri thang pa Blo gros rgyal mtshan dpal bzang
    po (1432–1488)
  author: གསེར་མདོག་པཎ་ཆེན་ཤཱཀྱ་མཆོག་ལྡན།
  description: 'Digital version 4.0 {Tibetan}; master xml (completed: 2012-09); head
    entries supplemented and linebreaks encoded, revision in process, no thematic
    TEI markup'
  source: https://sakyaresearch.org
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:Volker Caumanns (vc)
  - Editorial process:Volker Caumanns (vc), Mathias Fermer (mf)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:Volker Caumanns (vc)
  text_witnesses: https://sakyaresearch.org/sources/363
  bases:
    0f3a:
      title: Hagiography of sPyan snga Glang ri thang pa Blo gros rgyal mtshan dpal
        bzang po (1432–1488)
      order: 1
      base_file: 0f3a.txt
created_at: '2022-04-15T18:58:00.728740'
last_modified_at: '2022-04-15T18:58:00.728747'
quality: null
